coverage:
  status:
    patch: off
    project:
      default: false
      library:
        target: auto
        paths: ['!.*/tests/.*']
        threshold: 0.1%
      tests:
        target: auto
        paths: ['.*/tests/.*']
        threshold: 0.1%
codecov:
  require_ci_to_pass: false

