-- Content hash for upload deduplication.
--
-- content_hash: hex-encoded SHA-256 of the compressed .papyri artifact as
-- received by PUT /api/bundle (identical bytes to what `papyri upload`
-- computes client-side). The upload CLI sends this hash to GET /api/bundle
-- before uploading; when the stored hash for (module, version) matches, the
-- bundle is already ingested and the upload is skipped.
--
-- Nullable: rows written before this column existed leave it NULL.
--
-- Note: this hashes the full artifact, image bytes included. Autogenerated
-- images are non-deterministic across rebuilds, so a re-`papyri gen` run can
-- change the hash even when the documented API is unchanged. That only causes
-- a redundant re-upload (never a false "already uploaded"), so it is safe; a
-- future content-identity hash that excludes volatile assets is tracked in
-- PLAN.md.

ALTER TABLE bundles ADD COLUMN content_hash TEXT;
