[dask]
logo = "../dask-logo.png"
submodules = ["array"]
exclude = [ "dask.utils.Dispatch",
# target not implemented
'dask.highlevelgraph.HighLevelGraph.visualize',
'dask.order.graph_metrics'

]
#docs_path = "~/dev/dask/docs/source"
exec_failure = 'fallback'
