[distributed]
logo = "../dask-logo.png"
exclude = [
    # VisitTarget not implemented
    "distributed.comm.ucx",
    # misc
    "distributed.worker.Worker",
    "distributed.client.get_task_stream",
    "distributed.batched.BatchedSend",


] #docs_path = "~/dev/dask/docs/source"
exec_failure = 'fallback'
