[global]
module = 'distributed'
logo = "img/dask-logo.png"
exclude = [
    # misc
    "distributed.worker:Worker",
    "distributed.client:get_task_stream",
    "distributed.batched:BatchedSend",
    # imbalanced backticks https://github.com/dask/distributed/pull/5784
    "distributed.utils_comm:retry",
    "distributed._concurrent_futures_thread:ThreadPoolExecutor.__init__",
    #"ErrorHelper1-<class 'ValueError'>": [
    "distributed.protocol.core:dumps",
    "distributed.diagnostics.progress:MultiProgress",
    "distributed.diagnostics.progress:Progress",
    "distributed.shuffle._disk:DiskShardsBuffer",
    "distributed.shuffle._comms:CommShardsBuffer",
] #docs_path = "~/dev/dask/docs/source"
exec_failure = 'fallback'

[global.expected_errors]
NumpydocParseError = [
   "distributed.client:default_client",
   "distributed.utils:offload",
   "distributed.metrics:ContextMeter",
   "distributed.utils:run_in_executor_with_context",
]
