[global]
module = 'IPython'
logo = "img/ipython-logo.png"
exec_failure = "fallback"
docs_path = "~/dev/IPython/docs/source"
exec = true
execute_exclude_patterns = [
   'IPython.lib.display:Audio',
   'IPython.core.display_functions:display'
]
exclude = []
[global.expected_errors]
IncorrectInternalDocsLen = [
    "IPython.core.magics.namespace:NamespaceMagics.xdel",
]
TextSignatureParsingFailed = [
    "IPython.core.guarded_eval:SelectivePolicy",
    "IPython.core.oinspect:OInfo",
    "IPython.terminal.shortcuts:RuntimeBinding",
    "IPython.terminal.shortcuts:BaseBinding",
    "IPython.terminal.shortcuts:Binding",
    "IPython.utils.timing:clock2",
    "IPython.utils.timing:timings",
    "IPython.utils.timing:timings_out",
]
[global.implied_imports]
get_ipython = 'IPython:get_ipython'


[meta]
github_slug = 'IPython/IPython'
tag = '8.2.0'
pypi = 'ipython'
homepage = 'https://ipython.org/'
docspage = 'https://ipython.readthedocs.org/'
