[IPython]
logo = "../ipython-logo.png"
exec_failure = "fallback"
exec = true
exclude = [
    'IPython.core.magics.execution.ExecutionMagics.run',
    'IPython.core.magics.script.ScriptMagics.shebang',
    'IPython.core.magics.basic.BasicMagics.alias_magic',
]
