[matplotlib]
logo = "../matplotlib_logo.png"
wait_for_plt_show = false
exec_failure = "fallback"
submodules = [ "image", "pyplot", "axes", "axes._base", "dviread", "image",]
exclude = ['matplotlib._api',
           'matplotlib.pyplot.step',
           'matplotlib.pyplot.subplot_mosaic',
           'matplotlib._api.deprecation',
           'matplotlib.cm.unregister_cmap',
           'matplotlib.artist.Artist.set_sketch_params',
           'matplotlib.artist.Artist.set_clip_path',
           'matplotlib.artist.Artist.set_agg_filter',
           # .. ACCEPTS: comment
           'matplotlib.axes._axes.Axes.step',# .. Accepts:
           'matplotlib.axes._axes.Axes.pcolorfast',# .. Accepts:
           'matplotlib.patches.Rectangle.set_bounds',# .. Accepts:
           'matplotlib.axes._base._AxesBase.set_xlim',# .. Accepts:
           'matplotlib.axes._base._AxesBase.set_ylim', # .. Accepts:
           'matplotlib.spines.Spine.set_bounds', 
           # directive with space
           'matplotlib.axes._base._AxesBase.set_navigate_mode', # space directive
           'matplotlib.cm.ScalarMappable.set_clim', # .. ACCEPTS:
           'matplotlib.figure.FigureBase.subplot_mosaic', # .. note :: < with space
           # .. misc comments:
           'matplotlib.pyplot.fill_between',
           'matplotlib.pyplot.fill_betweenx',
           # visit_targets:
           'matplotlib.pyplot.pcolor',
           'matplotlib.pyplot.pcolormesh',
           'matplotlib.font_manager.FontProperties',
           'matplotlib.font_manager.FontManager.findfont',
           'matplotlib.fontconfig_pattern.FontconfigPatternParser',
           'matplotlib.colors',
           'matplotlib.fontconfig_pattern',
           'matplotlib.markers',
           'matplotlib.mathtext',
           'matplotlib.image.pil_to_array',
           'matplotlib.backend_bases.GraphicsContextBase.set_dashes',
           'matplotlib.backend_bases.GraphicsContextBase.get_dashes',
           'matplotlib.axes._axes.Axes.pcolormesh',
           'matplotlib.axes._axes.Axes.pcolor',
           'matplotlib.axes._axes.Axes.fill_betweenx',
           'matplotlib.axes._axes.Axes.fill_between',
           'matplotlib.axes._axes.Axes._fill_between_x_or_y'
           ]
