[matplotlib]
logo = "../matplotlib_logo.png"
wait_for_plt_show = false
exec_failure = "fallback"
submodules = [ "image", "pyplot", "axes", "axes._base", "dviread", "image",]
exclude = ['matplotlib._api']
