[global]
module = 'networkx'
execute_exclude_patterns = []

submodules = []

# docs_path = '~/dev/numpy/doc/source'

exec = true
exclude_jedi = ['networkx.algorithms.planarity.PlanarEmbedding']
exec_failure = 'fallback'
source = 'https://github.com/networkx/networkx'
exclude = [ 'networkx.algorithms.distance_measures.barycenter',
            'networkx.generators.geometric.geographical_threshold_graph',
           # `k`th parsing issue
            'networkx.algorithms.operators.product.power',
           #"ErrorHelper1-<class 'AssertionError'>"
             "networkx.algorithms.operators.product.power",
             "networkx.algorithms.centrality.betweenness._add_edge_keys",
             "networkx.algorithms.community.louvain.louvain_communities",
           # "ErrorHelper1-<class 'ValueError'>"
             "networkx.generators.geometric.waxman_graph",
           # "ErrorHelper1-<class 'papyri.errors.VisitCitationReferenceNotImplementedError'>"
             "networkx.generators.atlas.graph_atlas_g",
             "networkx.algorithms.graphical.is_graphical",
             "networkx.algorithms.graphical.is_valid_degree_sequence_erdos_gallai",
             "networkx.algorithms.graphical.is_valid_degree_sequence_havel_hakimi",
           # "ErrorHelper1-<class 'papyri.errors.VisitSubstitutionDefinitionNotImplementedError'>"
             "networkx.algorithms.approximation.vertex_cover",
             ]
logo = './nx.png'
[meta]
github_slug = 'networkx/networkx'
tag = 'networkx-2.7.1'
pypi = 'networkx'
homepage = 'https://networkx.org/'
docspage = 'https://networkx.org/documentation/stable/'
[networkx.implied_imports]
nx = 'networkx'
it = 'itertools'

