[global]
module = 'networkx'
execute_exclude_patterns = []

submodules = []

# docs_path = '~/dev/numpy/doc/source'

exec = true
exclude_jedi = ['networkx.algorithms.planarity.PlanarEmbedding']
exec_failure = 'fallback'
source = 'https://github.com/networkx/networkx'
exclude = [ 
             ]
logo = './img/nx.png'
[meta]
github_slug = 'networkx/networkx'
tag = 'networkx-2.7.1'
pypi = 'networkx'
homepage = 'https://networkx.org/'
docspage = 'https://networkx.org/documentation/stable/'
[global.implied_imports]
nx = 'networkx'
it = 'itertools'

[global.expected_errors]
VisitCitationReferenceNotImplementedError = [
    "networkx.algorithms.distance_measures:barycenter",
    "networkx.generators.atlas:graph_atlas_g",
    "networkx.algorithms.graphical:is_graphical",
    "networkx.algorithms.graphical:is_valid_degree_sequence_erdos_gallai",
    "networkx.algorithms.graphical:is_valid_degree_sequence_havel_hakimi",
]
WrongTypeAtField = [
    "networkx.generators.geometric:geographical_threshold_graph",
    "networkx.generators.geometric:waxman_graph",
    "networkx.algorithms.cycles:_johnson_cycle_search",
]
IncorrectInternalDocsLen = [
    "networkx.algorithms.community.louvain:louvain_communities",
]
