[numpy]
infer = false
execute_exclude_patterns = ['numpy._', 'numpy.testing._priv', 'numpy.errstate', 'numpy.seterr', 'numpy.bincount',
'numpy.core._multiarray_umath.bincount', 'numpy.core._multiarray_umath.datetime_as_string',
'numpy.core._multiarray_umath.normalize_axis_index', 'numpy.core._multiarray_umath.shares_memory',
'numpy.datetime_as_string', 'numpy.shares_memory', 'numpy.squeeze',
'numpy.average',
'numpy.ctypeslib', 'numpy.append', 'numpy.ma.core']
exclude = [
   'numpy.testing._private.nosetester.NoseTester',
   'numpy._pytesttester',
   # misc assertion errors:
   "numpy.ma.core.MaskedArray.resize",
   "numpy.polynomial.hermite.hermmulx",
   "numpy.polynomial.hermite_e.hermemulx",
   "numpy.polynomial.laguerre.lagmulx",
   # substitution Reference 
   'numpy.isscalar',
   # substitution definition not implmented
   'numpy.rollaxis',
   # comments not implemented
   'numpy.polyfit',
   "numpy.unique",
   "numpy.ma.extras.polyfit",
   "numpy.polynomial.chebyshev",
   "numpy.polynomial.polynomial.polyfit",
   "numpy.polynomial.polyutils.mapdomain",
   # missparsing of example sections.
   "numpy.percentile",
   # Citation Reference not implemented
   "numpy.fft",
   # numpydocs errors
   "numpy.polynomial._polybase.ABCPolyBase"
   ]
exec_failure = 'fallback'
source = 'https://github.com/numpy/numpy'
homepage = 'https://numpy.org'
docs = 'https://numpy.org/doc/stable/'
logo = '../numpy_logo.png'

