[numpy]
execute_exclude_patterns = ['numpy._','numpy.testing._priv', 'numpy.errstate', 'numpy.seterr', 'numpy.bincount',
'numpy.core._multiarray_umath.bincount', 'numpy.core._multiarray_umath.datetime_as_string',
'numpy.core._multiarray_umath.normalize_axis_index', 'numpy.core._multiarray_umath.shares_memory',
'numpy.datetime_as_string', 'numpy.shares_memory', 'numpy.squeeze',
'numpy.average',
'numpy.ctypeslib', 'numpy.append', 'numpy.ma.core',

# try to create a pager that waits for input
'numpy.lookfor',
# write directly to stdout
'numpy.info',
# Misc
'numpy.distutils',
]

submodules = ['distutils','typing']

# docs_path = '~/dev/numpy/doc/source'

exec = true
exclude = []
exec_failure = 'fallback'
source = 'https://github.com/numpy/numpy'
homepage = 'https://numpy.org'
docs = 'https://numpy.org/doc/stable/'
logo = './numpy_logo.png'
early_error = false

[meta]
github_slug = 'numpy/numpy'
tag = 'v1.22.3'
pypi = 'numpy'
homepage = 'https://numpy.org/'
docspage = 'https://numpy.org/doc/1.22//'


[numpy.expected_errors]
ValueError = [
    "numpy.core.shape_base._concatenate_shapes",
    ]
NumpydocParseError = [
    "numpy._from_dlpack",
    "numpy.typing._nested_sequence._NestedSequence",
    "numpy.polynomial._polybase.ABCPolyBase",
    ]
VisitCitationReferenceNotImplementedError = [
    "numpy.fft",
    ]
VisitSubstitutionDefinitionNotImplementedError = [
    "numpy.rollaxis",
    ]
IncorrectInternalDocsLen = [
    "numpy.tensordot",
    "numpy.lib._datasource.DataSource._splitzipext",
    "numpy.core._internal._view_is_safe",
    "numpy.distutils.misc_util.Configuration.__init__",]
AssertionError = [ 
    "numpy.polynomial.polynomial.polyvalfromroots",
    "numpy.random.bit_generator.ISeedSequence.generate_state",
]

