[global]

module = 'numpy'

exclude = [
'numpy:tensordot',
]

execute_exclude_patterns = [
'numpy:set_numeric_ops',
'numpy._',
'numpy.testing._priv',
'numpy.errstate',
'numpy.seterr',
'numpy.bincount',
'numpy.core._multiarray_umath.bincount',
'numpy.core._multiarray_umath.datetime_as_string',
'numpy.core._multiarray_umath.normalize_axis_index',
'numpy.core._multiarray_umath.shares_memory',
'numpy.datetime_as_string',
'numpy.shares_memory',
'numpy.squeeze',
'numpy.average',
'numpy.ctypeslib',
'numpy.append',
'numpy.ma.core',
'numpy.core.umath_tests',
# try to create a pager that waits for input
'numpy.lookfor',
# write directly to stdout
'numpy.info',
# Misc
'numpy.distutils',
'numpy.char.multiply',
'numpy.polynomial.chebyshev.chebinterpolate',
'numpy.lib.npyio._read',
'numpy.polynomial._polybase:ABCPolyBase',
'numpy.distutils.misc_util:Configuration.__init__',
]

submodules = [
    'array_api',
    'compat',
    'core',
    'ctypeslib',
    'doc',
    'fft',
    'lib',
    'linalg',
    'ma',
    'matlib',
    'matrixlib',
    'polynomial',
    'random',
    'testing',
    'tests',
    'typing',
    'version',
]

docs_path = '~/dev/numpy/doc/source'

exec = true
narrative_exclude = [
   'doc/source/reference/arrays.ndarray.rst',
   'doc/source/user/how-to-how-to.rst',
   'doc/source/f2py/usage.rst',
   'doc/source/_templates/',
]
exec_failure = 'fallback'
source = 'https://github.com/numpy/numpy'
homepage = 'https://numpy.org'
docs = 'https://numpy.org/doc/stable/'
logo = './img/numpy_logo.png'
early_error = false

[meta]
github_slug = 'numpy/numpy'
tag = 'v{version}'
pypi = 'numpy'
homepage = 'https://numpy.org/'
docspage = 'https://numpy.org/doc/1.26/'


[global.expected_errors]
VisitCitationReferenceNotImplementedError = ["numpy.fft"]

