[global]
module = 'papyri'
submodules = ['examples']
examples_folder = '~/dev/papyri/docs/examples/'
logo = "../papyri-logo.png"
docs_path = "~/dev/papyri/docs"
exec = true
exec_failure = 'raise'
exclude= ["papyri.utils:FullQual","papyri.utils:Cannonical" ]

[meta]
github_slug = 'jupyter/papyri'
tag = '{{version}}'
pypi = 'papyri'
