[global]
module = 'papyri'
submodules = ['examples']
examples_folder = '~/dev/papyri/docs/examples/'
logo = "../papyri-logo.png"
docs_path = "~/dev/papyri/docs"
execute_doctests = true
exec_failure = 'raise'
exclude= ["papyri.utils:FullQual","papyri.utils:Canonical" ]
[global.directives]
mydirective='papyri.examples:_mydirective_handler'
# To silently drop a directive, map it to papyri.directives:drop:
# testsetup = 'papyri.directives:drop'


[meta]
github_slug = 'jupyter/papyri'
tag = '{{version}}'
pypi = 'papyri'
