[global]
module = 'scipy'
logo = "../scipy_logo.png"
exec = true
submodules = [ "signal","misc"]
exclude = [
    # https://github.com/stsewd/tree-sitter-rst/issues/31
    "scipy.interpolate._fitpack_py.splprep",
    "scipy.sparse._construct._compressed_sparse_stack",
    "scipy.sparse._construct._stack_along_minor_axis",
    # OTHER.

    "scipy.sparse.csgraph._traversal.breadth_first_tree",
    "scipy.sparse.csgraph._traversal.depth_first_tree",

    # this just prints quad docs to stdout and should be removed.
    "scipy.integrate._quadpack_py.quad_explain",
    # Example is incorrect https://github.com/scipy/scipy/issues/15595
    "scipy.signal._peak_finding._identify_ridge_lines",
    "scipy.stats._continuous_distns.crystalball_gen._pdf",
    "scipy.stats._ksstats._kolmogn_PelzGood",
    "scipy.stats._discrete_distns.betabinom_gen",
    "scipy.sparse.csgraph._min_spanning_tree.minimum_spanning_tree",
    "scipy.stats._morestats.wilcoxon",
    "scipy.stats._distn_infrastructure.rv_continuous",
    "scipy.stats._stats_py.moment",
    "scipy.stats._mannwhitneyu.mannwhitneyu",
    "scipy.stats._resampling.bootstrap",
    "scipy.sparse.linalg._expm_multiply.expm_multiply",
            ]
exclude_jedi = [
    "scipy.linalg._sketches.clarkson_woodruff_transform",
    "scipy.optimize._lsq.least_squares.least_squares",
    "scipy.linalg.decomp_qr.qr",
    "scipy.linalg._decomp_cossin.cossin",
    "scipy.linalg.decomp.eigh_tridiagonal",
    "scipy.linalg.decomp.eigvalsh_tridiagonal",
    "scipy.linalg.decomp.hessenberg",
    "scipy.linalg.decomp_svd.null_space",
    "scipy.signal.bsplines.bspline",
    ]

execute_exclude_patterns = [
    'scipy._lib._uarray._backend.determine_backend_multi',
    'scipy.integrate._quadrature._qmc_quad',
    'scipy.interpolate._bspl.evaluate_all_bspl',
    'scipy.optimize._root.root',
    'scipy.signal._filter_design.normalize',
    'scipy.signal._signaltools.filtfilt',
    'scipy.stats._axis_nan_policy._broadcast_array_shapes_remove_axis',
    'scipy.stats._multivariate.multivariate_normal_frozen.__init__',
    'scipy.stats._multivariate.multivariate_t_frozen.__init__',
    'scipy.stats._stats_py._ttest_nans',
    'scipy.io.matlab._mio5.varmats_from_mat',
    'scipy.io.matlab._byteordercodes.to_numpy_code',
    'scipy._lib._uarray._backend.determine_backend',
    'scipy._lib._uarray._backend.all_of_type',
    'scipy._lib._util._nan_allsame',
    ]
exec_failure = "fallback"
jedi_failure_mode = "log"
early_error = false

[meta]
github_slug = 'scipy/scipy'
tag = 'v1.8.0'
pypi = 'scipy'
homepage = 'https://scipy.org/'
docspage = 'https://docs.scipy.org/doc/scipy/'
[global.implied_imports]
ua = 'scipy._lib.uarray'
array = 'numpy:array'
arange = 'numpy:arange'
[global.expected_errors]
IncorrectInternalDocsLen = [
    "scipy.linalg._decomp.cdf2rdf",
    "scipy.optimize._lsq.common.regularized_lsq_operator",
    "scipy.optimize._trustregion_constr.tr_interior_point.BarrierSubproblem.gradient_and_jacobian",
    "scipy.optimize._trustregion_constr.tr_interior_point.tr_interior_point",
    "scipy.signal._filter_design._ellipdeg",
    "scipy.signal._spline.symiirorder1",
    "scipy.signal._spline.symiirorder2",
    "scipy.sparse._bsr.bsr_matrix.check_format",
    ]
VisitCitationReferenceNotImplementedError = [
    "scipy.optimize._nonlin.anderson",
    "scipy.optimize._zeros_py.brenth",
    "scipy.optimize._zeros_py.brentq",
    "scipy.optimize._lsq.least_squares.least_squares",
    "scipy.optimize._lsq.lsq_linear.lsq_linear",
    "scipy.optimize._zeros_py.ridder",
    "scipy.special._orthogonal",
    "scipy.special._orthogonal.roots_chebyc",
    "scipy.special._orthogonal.roots_gegenbauer",
    "scipy.special._orthogonal.roots_hermite",
    "scipy.special._orthogonal.roots_hermitenorm",
    "scipy.special._orthogonal.roots_jacobi",
    "scipy.special._orthogonal.roots_sh_jacobi",
    "scipy.special._orthogonal.roots_laguerre",
    "scipy.special._orthogonal.roots_genlaguerre",
    "scipy.special._orthogonal.roots_legendre",
    "scipy.special._basic.polygamma",
    "scipy.special._orthogonal.roots_sh_legendre",
    "scipy.special._orthogonal.roots_chebys",
    "scipy.special._orthogonal.roots_chebyt",
    "scipy.special._orthogonal.roots_chebyu",
    "scipy.special._orthogonal.roots_sh_chebyt",
    "scipy.special._orthogonal.roots_sh_chebyu",
    "scipy.special._basic.zeta",
    "scipy.interpolate.interpnd.CloughTocher2DInterpolator",
    "scipy.optimize._lsq.dogbox",
    "scipy.optimize._lsq.trf",
    "scipy.optimize._nonlin.Anderson",
    "scipy.special._orthogonal._pbcf",
    "scipy.spatial._spherical_voronoi.SphericalVoronoi",
    "scipy.spatial._spherical_voronoi.calculate_solid_angles",
    "scipy.integrate._ode.ode",
    ]
AssertionError = [
    "scipy.optimize._linprog_ip._ip_hsd",
    "scipy.special._orthogonal._compute_tauk",
    ]
NumpydocParseError = [
    "scipy.optimize._linprog_doc._linprog_highs_doc",
    "scipy.optimize._linprog_doc._linprog_highs_ds_doc",
    "scipy.optimize._linprog_doc._linprog_highs_ipm_doc",
    "scipy.optimize._linprog_doc._linprog_ip_doc",
    "scipy.optimize._linprog_doc._linprog_rs_doc",
    "scipy.optimize._linprog_doc._linprog_simplex_doc",
    "scipy.optimize._linprog_highs._linprog_highs",
    "scipy.optimize._linprog_ip._linprog_ip",
    "scipy.optimize._linprog_rs._linprog_rs",
    "scipy.optimize._linprog_simplex._linprog_simplex",
    "scipy.optimize._optimize._minimize_powell",
    "scipy.optimize._qap._quadratic_assignment_2opt",
    "scipy.optimize._qap._quadratic_assignment_faq",
    "scipy.stats._discrete_distns.geom_gen",
    "scipy.stats._discrete_distns.planck_gen",
    ]
SpaceAfterBlockDirectiveError = [
    "scipy.optimize._tnc._minimize_tnc",
    ]
    
