[global]
module = 'scipy'
logo = "img/scipy_logo.png"
execute_doctests = true
docs_path = '~/dev/scipy/doc/source'
submodules = [ "signal","misc"]
exclude = [
    # IncorrectInternalDocsLen
    "scipy.stats._ksstats:_kolmogn_PelzGood",

    # contain ascii diagram
    "scipy.stats._continuous_distns:crystalball_gen._pdf",

    # assert len(tsc) in (0, 1), (tsc, data)
    "scipy.io.matlab._mio5",

    # Tree SIttr parse error
    "scipy.stats._multivariate:matrix_t_frozen.logpdf",
    "scipy.stats._multivariate:matrix_t_gen.logpdf",

            ]

exec_failure = "fallback"
jedi_failure_mode = "log"
early_error = false

narrative_exclude = [
   'doc/source/tutorial/optimize.rst',
   'doc/source/tutorial/signal.rst',
   'doc/source/tutorial/stats/continuous_wrapcauchy.rst',
   'doc/source/building/blas_lapack.rst',
]


[meta]
github_slug = 'scipy/scipy'
tag = 'v{{version}}'
pypi = 'scipy'
homepage = 'https://scipy.org/'
docspage = 'https://docs.scipy.org/doc/scipy/'
[global.implied_imports]
scipy = 'scipy'
ua = 'scipy._lib.uarray'
array = 'numpy:array'
arange = 'numpy:arange'
[global.expected_errors]
IncorrectInternalDocsLen = [
    "scipy.signal._filter_design:_ellipdeg",
    "scipy.optimize._lsq.common:regularized_lsq_operator",
    "scipy.optimize._trustregion_constr.tr_interior_point:tr_interior_point",
    "scipy.optimize._trustregion_constr.tr_interior_point:BarrierSubproblem.gradient_and_jacobian",
    "scipy.integrate._rules._base:_split_subregion",
    "scipy.integrate._cubature:_VariableTransform.inv",
    "scipy.integrate._cubature:_VariableTransform.__call__",
    "scipy._lib._docscrape:NumpyDocString._parse_see_also",
]
AssertionError = [
    "scipy.special._multiufuncs:MultiUFunc",
]
NumpydocParseError = [
    "scipy.optimize._linprog_highs:_linprog_highs",
    "scipy.optimize._linprog_doc:_linprog_highs_doc",
    "scipy.optimize._linprog_doc:_linprog_highs_ds_doc",
    "scipy.optimize._linprog_doc:_linprog_highs_ipm_doc",
    "scipy.optimize._linprog_ip:_linprog_ip",
    "scipy.optimize._linprog_doc:_linprog_ip_doc",
    "scipy.optimize._linprog_rs:_linprog_rs",
    "scipy.optimize._linprog_doc:_linprog_rs_doc",
    "scipy.optimize._linprog_simplex:_linprog_simplex",
    "scipy.optimize._linprog_doc:_linprog_simplex_doc",
    "scipy.optimize._optimize:_minimize_powell",
    "scipy.optimize._qap:_quadratic_assignment_2opt",
    "scipy.optimize._qap:_quadratic_assignment_faq",
    "scipy.special._specfun:jdzo",
    "scipy._lib._docscrape:NumpyDocString._parse_index",
]
TreeSitterParseError = [
    "scipy.sparse.linalg._isolve._gcrotmk:gcrotmk",
    "scipy.sparse.linalg._isolve.lgmres:lgmres",
    "scipy.sparse.linalg._isolve.tfqmr:tfqmr",
    "scipy.spatial.transform._rigid_transform:RigidTransform",
]
ExampleError1 = [
    "scipy.stats._mstats_basic:tmax",
    "scipy.stats._mstats_basic:tmean",
]

[global.directives]
legacy   = 'papyri.directives:drop'
currentmodule   = 'papyri.directives:drop'
contents   = 'papyri.directives:drop'
automethod   = 'papyri.directives:drop'
autoproperty   = 'papyri.directives:drop'
versionremoved   = 'papyri.directives:drop'
sectionauthor   = 'papyri.directives:drop'
module   = 'papyri.directives:drop'
moduleauthor   = 'papyri.directives:drop'
"scipy-optimize:function"   = 'papyri.directives:drop'
"array-api-support-per-module"   = 'papyri.directives:drop'
"dev:index"   = 'papyri.directives:drop'
"array-api-support-per-function"   = 'papyri.directives:drop'
