[global]
module = 'scipy'
logo = "../scipy_logo.png"
exec = true
submodules = [ "signal","misc"]
exclude = [ "scipy.sparse.csgraph._traversal.breadth_first_tree",
    "scipy.sparse.csgraph._traversal.depth_first_tree",

    # this just prints quad docs to stdout and should be removed.
    "scipy.integrate._quadpack_py.quad_explain",
    # Example is incorrect https://github.com/scipy/scipy/issues/15595
    "scipy.signal._peak_finding._identify_ridge_lines",
            ]
exclude_jedi = [
    "scipy.linalg._sketches.clarkson_woodruff_transform",
    "scipy.optimize._lsq.least_squares.least_squares",
    "scipy.linalg.decomp_qr.qr",
    "scipy.linalg._decomp_cossin.cossin",
    "scipy.linalg.decomp.eigh_tridiagonal",
    "scipy.linalg.decomp.eigvalsh_tridiagonal",
    "scipy.linalg.decomp.hessenberg",
    "scipy.linalg.decomp_svd.null_space",
    "scipy.signal.bsplines.bspline",
    ]

execute_exclude_patterns = [
    'scipy._lib._uarray._backend.determine_backend_multi',
    'scipy.interpolate._bspl.evaluate_all_bspl']
exec_failure = "fallback"
jedi_failure_mode = "log"
early_error = false

[meta]
github_slug = 'scipy/scipy'
tag = 'v1.8.0'
pypi = 'scipy'
homepage = 'https://scipy.org/'
docspage = 'https://docs.scipy.org/doc/scipy/'
[global.implied_imports]
ua = 'scipy._lib.uarray'
array = 'numpy:array'
arange = 'numpy:arange'
[global.expected_errors]
IncorrectInternalDocsLen = [
    "scipy.signal._spline.symiirorder1", "scipy.signal._spline.symiirorder2",
    "scipy.signal._filter_design._ellipdeg", "scipy.special._logsumexp.log_softmax", "scipy.linalg._decomp.cdf2rdf",
    "scipy.linalg._special_matrices.fiedler", "scipy.interpolate._fitpack_impl.bisplev",
    "scipy.interpolate._fitpack_py.spalde", "scipy.interpolate._fitpack_impl.spalde",
    "scipy.optimize._lsq.common.regularized_lsq_operator",
    "scipy.optimize._trustregion_constr.tr_interior_point.tr_interior_point",
    "scipy.sparse._bsr.bsr_matrix.check_format",
    "scipy.optimize._trustregion_constr.tr_interior_point.BarrierSubproblem.gradient_and_jacobian",
    ]
VisitCitationReferenceNotImplementedError = [
    "scipy.optimize._nonlin.anderson",
    "scipy.optimize._zeros_py.brenth",
    "scipy.optimize._zeros_py.brentq",
    "scipy.optimize._lsq.least_squares.least_squares",
    "scipy.optimize._lsq.lsq_linear.lsq_linear",
    "scipy.optimize._zeros_py.ridder",
    "scipy.special._orthogonal",
    "scipy.special._orthogonal.roots_chebyc",
    "scipy.special._orthogonal.roots_gegenbauer",
    "scipy.special._orthogonal.roots_hermite",
    "scipy.special._orthogonal.roots_hermitenorm",
    "scipy.special._orthogonal.roots_jacobi",
    "scipy.special._orthogonal.roots_sh_jacobi",
    "scipy.special._orthogonal.roots_laguerre",
    "scipy.special._orthogonal.roots_genlaguerre",
    "scipy.special._orthogonal.roots_legendre",
    "scipy.special._basic.polygamma",
    "scipy.special._orthogonal.roots_sh_legendre",
    "scipy.special._orthogonal.roots_chebys",
    "scipy.special._orthogonal.roots_chebyt",
    "scipy.special._orthogonal.roots_chebyu",
    "scipy.special._orthogonal.roots_sh_chebyt",
    "scipy.special._orthogonal.roots_sh_chebyu",
    "scipy.special._basic.zeta",
    "scipy.interpolate.interpnd.CloughTocher2DInterpolator",
    "scipy.optimize._lsq.dogbox",
    "scipy.optimize._lsq.trf",
    "scipy.optimize._nonlin.Anderson",
    "scipy.special._orthogonal._pbcf",
    "scipy.spatial._spherical_voronoi.SphericalVoronoi",
    "scipy.spatial._spherical_voronoi.calculate_solid_angles",
    ]
ExampleError1 = [ "scipy.sparse.csgraph._min_spanning_tree.minimum_spanning_tree",
                  "scipy.optimize._root.root", "scipy.interpolate._fitpack2.LSQSphereBivariateSpline",
                    "scipy.interpolate._fitpack2.SmoothSphereBivariateSpline", "scipy.sparse.linalg._eigen._svds.svds",]
AssertionError = [
    "scipy.signal._peak_finding.find_peaks_cwt",
    "scipy.signal._peak_finding._filter_ridge_lines", "scipy.integrate._quadrature.cumtrapz",
    "scipy.integrate._quadpack_py.dblquad", "scipy.integrate._odepack_py.odeint", "scipy.integrate._quadrature.simps",
    "scipy.integrate._quadrature.trapz", "scipy.optimize._linprog_ip._ip_hsd",
    "scipy.special._orthogonal._compute_tauk",
    ]
NumpydocParseError = [
    "scipy.optimize._linprog_highs._linprog_highs", "scipy.optimize._linprog_doc._linprog_highs_doc",
    "scipy.optimize._linprog_doc._linprog_highs_ds_doc", "scipy.optimize._linprog_doc._linprog_highs_ipm_doc",
    "scipy.optimize._linprog_ip._linprog_ip", "scipy.optimize._linprog_doc._linprog_ip_doc",
    "scipy.optimize._linprog_rs._linprog_rs", "scipy.optimize._linprog_doc._linprog_rs_doc",
    "scipy.optimize._linprog_simplex._linprog_simplex", "scipy.optimize._linprog_doc._linprog_simplex_doc",
    "scipy.optimize._qap._quadratic_assignment_2opt", "scipy.optimize._qap._quadratic_assignment_faq",
    ]
