[global]
module = 'skimage'
logo = "img/skimage-logo.png"
exec_failure = "fallback"
submodules = [ "morphology", "color", "data", "draw", "exposure", "io", "graph", "segmentation", "transform", "util"]
exclude = [
          ]
exclude_jedi = ['skimage.viewer.plugins.base.Plugin']
[global.expected_errors]
WrongTypeAtField = [
    "skimage.morphology._skeletonize:medial_axis",
]
VisitCitationReferenceNotImplementedError = [
    "skimage.morphology._skeletonize:skeletonize",
    "skimage.morphology._skeletonize:skeletonize_3d",
    "skimage.morphology._skeletonize:skeletonize_2d",
    "skimage.morphology._skeletonize_3d_cy",
]
