[global]
module = 'xarray'
execute_exclude_patterns = []

submodules = []


execute_doctests = true
exclude = [
]
exec_failure = 'fallback'
source = 'https://github.com/pydata/xarray'
logo = './img/xarray.png'
early_error = false

[meta]
github_slug = 'pydata/xarray'
tag = '2022.3.0'
pypi = 'xarray'
homepage = 'https://docs.xarray.dev/'
docs = 'https://docs.xarray.dev/en/stable/'

[global.implied_imports]
xr = 'xarray'
pd = 'pandas'


[global.expected_errors]
AssertionError = [
    "xarray.core.dataarray:DataArray.drop_vars",
    "xarray.core.dataarray:DataArray.convert_calendar",
    "xarray.core.dataset:Dataset.convert_calendar",
]
