#!/usr/bin/env python3.13
"""Generate viewer/src/lib/ir-schema.ts from papyri.nodes annotations.

The viewer's IR stats panel uses this static schema to surface 0-counts for
fields / union members that the IR could legally contain but the scanned
bundles never did. Re-run this script whenever node types or annotations in
papyri/nodes.py change.
"""

from __future__ import annotations

import json
import types
import typing
from pathlib import Path

# Import populates TAG_MAP via @register decorators on Node subclasses.
import papyri.nodes  # noqa: F401
from papyri.node_base import TAG_MAP, Node
from papyri.serde import get_type_hints

PRIMITIVE_NAMES: dict[type, str] = {
    str: "string",
    bool: "boolean",
    int: "number",
    float: "number",
    type(None): "null",
}


def _flatten(ann: typing.Any, out: set[str], inside_array: bool) -> bool:
    """Walk an annotation tree.

    Mutates ``out`` with the set of value-type tags that the field can legally
    hold (IR node class names + primitive tags 'string'/'number'/'boolean'/
    'null'/'object'). Returns True if the field's top level is array-like
    (tuple[X, ...] or list[X]) — the caller adds the synthetic '[]' marker so
    empty arrays show up as a 0-pill rather than going missing.
    """
    origin = typing.get_origin(ann)
    if isinstance(ann, types.UnionType) or origin is typing.Union:
        is_array = False
        for arg in ann.__args__:
            is_array = _flatten(arg, out, inside_array) or is_array
        return is_array
    if origin in (list, tuple):
        # tuple[T, ...] / list[T]: drill into the element type. Ellipsis args
        # carry no type info.
        for arg in ann.__args__:
            if arg is Ellipsis:
                continue
            _flatten(arg, out, inside_array=True)
        return not inside_array
    if origin is dict:
        out.add("object")
        return False
    if ann in PRIMITIVE_NAMES:
        out.add(PRIMITIVE_NAMES[ann])
        return False
    if isinstance(ann, type) and issubclass(ann, Node):
        out.add(ann.__name__)
        return False
    # Anything else (custom dict-ish payloads, etc.) — call it 'object' so the
    # pill at least appears.
    out.add("object")
    return False


def field_schema(ann: typing.Any) -> dict[str, typing.Any]:
    types_: set[str] = set()
    is_array = _flatten(ann, types_, inside_array=False)
    if is_array:
        # Empty arrays serialise as [] — the stats walker buckets them under
        # this tag, so declare it as a legal value too.
        types_.add("[]")
    return {"array": is_array, "types": sorted(types_)}


def build_schema() -> dict[str, dict[str, dict[str, typing.Any]]]:
    schema: dict[str, dict[str, dict[str, typing.Any]]] = {}
    for cls in TAG_MAP:
        if not isinstance(cls, type) or not issubclass(cls, Node):
            continue
        try:
            hints = get_type_hints(cls)  # type: ignore[arg-type]
        except Exception as exc:  # pragma: no cover - defensive
            print(f"# skipping {cls.__name__}: {exc}")
            continue
        fields = {name: field_schema(ann) for name, ann in hints.items()}
        schema[cls.__name__] = fields
    return schema


HEADER = """\
// AUTO-GENERATED by scripts/gen_ir_schema.py — do not edit by hand.
//
// Maps each IR node type to its declared fields and the set of value types
// each field is allowed to carry, derived from the Python annotations in
// papyri/nodes.py. The viewer's IR stats panel uses this to surface
// 0-counts: union members and fields that *could* exist but were never
// observed in any scanned bundle.

export interface IRFieldSchema {
  /** True when the field is tuple[T, ...] or list[T] at the top level. */
  array: boolean;
  /** Sorted list of legal value-type tags (IR class names + primitive tags). */
  types: readonly string[];
}

export type IRSchema = Readonly<Record<string, Readonly<Record<string, IRFieldSchema>>>>;

export const IR_SCHEMA: IRSchema = """


def main() -> None:
    schema = build_schema()
    body = json.dumps(schema, indent=2, sort_keys=True)
    out_path = Path(__file__).resolve().parent.parent / "viewer/src/lib/ir-schema.ts"
    out_path.write_text(HEADER + body + " as const;\n")
    print(f"wrote {out_path} ({len(schema)} node types)")
    print("run `pnpm -C viewer run format` to apply Prettier style.")


if __name__ == "__main__":
    main()
