# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linters

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Just Cause'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit flake8 black mypy pipdeptree flake8-bugbear
        flit install --symlink
    - name: dependency tree
      run: |
        pipdeptree
    - name: dependency tree (reversed)
      run: |
        pipdeptree -r
    - name: Lint with black
      run: |
        black --check papyri
    - name: Lint with flake8
      run: |
        flake8 papyri
    - name: Test with mypy
      run: |
        python3 -m pip install types-requests types-cachetools types-toml
        mypy papyri
