# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 
    inputs:
      name:
        description: 'Reason'
        required: false
        default: 'Just Cause'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flit flake8 black scipy numpy matplotlib 'velin>=0.0.5' pytest-trio mypy tree_sitter coverage
        flit install --symlink
        git clone https://github.com/stsewd/tree-sitter-rst
        papyri build-parser
    - name: Test with pytest
      run: |
        pytest --cov=papyri
        ls -al
    - name: Misc cli
      run: |
        coverage run -m papyri --help
        ls -al
    - name: Self gen
      run: |
        coverage run -a -m papyri gen examples/papyri.toml  --exec
        sleep 1 # time for coverage to write its stuff
        coverage run -a -m papyri ingest  --no-relink ~/.papyri/data/papyri_0.0.8
        coverage run -a -m papyri render --ascii
        # coverage html
        # papyri serve
        ls -al
    - name: Lint with black
      run: |
        black --check papyri
    - name: Test with mypy
      run: |
        python3 -m pip install types-requests types-cachetools types-toml
        mypy papyri
    - name: Convert .coverage sql to xml for upload
      run: |
        converage xml
        ls -la
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
